### ISSUE TITLE
Update wiki docs

### ISSUE THREAD

**Issue by esell** [mspnp/template-building-blocks#187]
Working through the example on https://github.com/mspnp/template-building-blocks/wiki/Use-Template-Building-Blocks-version-2-Command-Line and I came across what looks like an outdated command. The example has:

`node index.js  -b vnet -g testRG -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -l westus -p .\spec\parameters\vnet-parameters.json -o test.json --deploy`

but I believe it should be:

`node index.js -g testRG -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -l westus -p ./spec/Parameters/vnet-parameters.json -o test.json --deploy`

Notice that the `-b` flag is removed and that the path to the parameters file has an uppercase "P" for the parameters directory. Otherwise it breaks on linux :).

**Comment by Petertaylor9999** [comment]
Thanks for the feedback - the Template Building Blocks are still in active development and we're updating the documentation in stages. But you are correct, that is the correct syntax for the current command line!
