### ISSUE TITLE
Enhancement: multiple parameters files

### ISSUE THREAD

**Issue by esell** [mspnp/template-building-blocks#195]
Hey all, first off this is a great tool, thanks for putting it together.

Would it make sense to support multiple parameters files that can then be combined into a single file? The use case is: people want to create a JSON file per NSG (or some other type of resource) and then have those files all squashed into a single JSON file. 

The idea is that it might be easier to manage if you had a single NSG per file instead of potentially having 20+ NSGs in one file.

Thoughts?

**Comment by Petertaylor9999** [comment]
There's a similar mechanism in this new version of the tool - named defaults. You'll be able to specify a single NSG rule or multiple NSG rules using only a single name in the parameter object that references a default JSON object. I'm working on the documentation right now.
