### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by matousrokos** [mspnp/template-building-blocks#286]
There is a broken link with [this address ](https://github.com/mspnp/template-building-blocks/tree/master/scenarios/vnet-n-subnet/parameters) on [this Wiki page](https://github.com/mspnp/template-building-blocks/wiki/VNet-(v1)). Basically parameter files are missing which is a bit critical for Building Blocks

**Comment by Petertaylor9999** [comment]
Thanks for opening this issue - I've fixed the link.
