### ISSUE TITLE
Incorrect tgz file name in the Windows install wiki page

### ISSUE THREAD

**Issue by lararubbelke** [mspnp/template-building-blocks#290]
The name of the tgz file name in the Windows install instructions is azure-building-blocks-1.0.0.tgz, and the file is named mspnp-azure-building-blocks-1.0.0.tgz.  

npm -g install azure-building-blocks-1.0.0.tgz

**Comment by telmosampaio** [comment]
Thanks Lara, we fixed that in the Wiki. We are about to publish the npm package. When that is live I will add a comment here and close the issue.

**Comment by telmosampaio** [comment]
Fixed. Check the wiki: https://github.com/mspnp/template-building-blocks/wiki
And the scenarios: https://github.com/mspnp/template-building-blocks/tree/master/scenarios
