### ISSUE TITLE
"sudo npm pack" fails in template-building-blocks/src on Ubuntu

### ISSUE THREAD

**Issue by richeney** [mspnp/template-building-blocks#307]
I'm following the Linux install steps on Ubuntu, and it fails in both an Azure VM and in bash on Windows.

Screen output here, and npm-debug.log(.txt) attached:

richeney@azbb:~/template-building-blocks/src$ sudo npm pack
npm ERR! addLocal Could not install /home/richeney/template-building-blocks/src
npm ERR! Linux 4.4.0-92-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "pack"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! code EISDIR
npm ERR! errno -21
[npm-debug.log.txt](https://github.com/mspnp/template-building-blocks/files/1280876/npm-debug.log.txt)

npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/richeney/template-building-blocks/src/npm-debug.log

**Comment by telmosampaio** [comment]
Please follow the instructions from https://github.com/mspnp/template-building-blocks/wiki to install the building blocks. To pack the way you were doing, make sure you are in the main folder, not the src folder.
