### ISSUE TITLE
Installing azbb without ever having logged into azure results in incorrect error message

### ISSUE THREAD

**Issue by Petertaylor9999** [mspnp/template-building-blocks#309]
Steps to repro:

Environment: az installed, npm installed, node installed

1. Open new cmd.exe command prompt.
2. Create new directory. Navigate to new directory.
3. Install azbb ('npm install....')
4. Attempt to deploy ('azbb -p <local path>.json...)

Result: 
```
  error: error executing az
  status: 1
  arguments: group exists --name testRG
```

Note that testRG does not exist as a resource group in Azure.
Logging in via `az login` fixes the issue.

**Comment by atoakley** [comment]
This error may be misleading.  This error is thrown when executing the az command returns a non-zero (i.e. successful) status code.  Whenever a non-zero error code is returned, we throw an error with the message "error executing az", the error code, and the arguments that were passed to az.  You can run the az command and pass those same arguments and see the actual error.  In certain scenarios, we may be able to display this message, so I will look into that.

**Comment by atoakley** [comment]
PR #311 should help make this error message clearer.
