### ISSUE TITLE
Step 4 in Wiki on installing azbb in the cloud shell fails

### ISSUE THREAD

**Issue by richstep** [mspnp/template-building-blocks#321]
Step 4 fails with a permissions issue.

To solve the issue:

You can eliminate step 3 and replace step 4 with this:
echo 'export PATH="$HOME/.npm-global/bin:$PATH"' >> ~/.bashrc

https://github.com/mspnp/template-building-blocks/wiki/Install-Azure-Building-Blocks-in-Azure-Cloud-Shell

**Comment by Petertaylor9999** [comment]
Hi Rich - what permissions issue do you encounter at step 4?

**Comment by lukeb1961** [comment]
3.  Either use vi or nano to open the ~./bashrc configuration file for editing:

  vi ~./bashrc

shouldn't that be referring to  ~/.bashrc ?

**Comment by Petertaylor9999** [comment]
Yes, you are correct. I fixed the document.
