### ISSUE TITLE
Deploying VM-Simple.json fails

### ISSUE THREAD

**Issue by KevinRemde** [mspnp/template-building-blocks#323]
https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-simple.json 

I have the file local, and from PowerShell I run this command:
azbb -g RG-azbb -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -l eastus -p .\vm-simple.json --deploy

(Where xxx's are obviously my proper subscription ID) 

The RG is created, as are the Public IP and Storage Account, but I get four deployment errors such as this:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidResourceReference\",\r\n    \"message\": \"Resource /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-azbb2/providers/Microsoft.Network/virtualNetworks/msft-hub-vnet/subnets/mgmt referenced by resource /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-azbb2/providers/Microsoft.Network/networkInterfaces/jb-vm1-nic1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.\",\r\n    \"details\": []\r\n  }\r\n}"}]}

Should I not be attempting to deploy this VM-Simple.json directly?

**Comment by Petertaylor9999** [comment]
Hi Kevin - that file includes the settings for a VM only. That JSON file references a VNet and subnet that you haven't deployed yet. You can deploy the VNet either by deploying '/scenarios/vnet/vnet-simple.json' first, or, if you want to deploy everything at once you can go to the '/scenarios/tutorials/` folder and deploy 'tutorial-3.json'. There will be a tutorial explaining that file up shortly.

**Comment by atoakley** [comment]
Kevin - I have updated the vm-simple.json to contain a virtual network that will allow this sample to run as a standalone file now.

**Comment by KevinRemde** [comment]
Awesome.  Thanks for the clarification, Peter, and the fix, atoakley.
