### ISSUE TITLE
Python vs Node

### ISSUE THREAD

**Issue by rcarmo** [mspnp/template-building-blocks#330]
As much as I appreciate the ease of use of azbb, I have to ask for a Python equivalent -- many organisations simply refuse to use Node as part of their sysadmin toolchains, given its brittleness and lack of fit with Python-based tooling and libraries.

**Comment by telmosampaio** [comment]
We are working on a roadmap for that. Stay tuned.

**Comment by ckittel** [comment]
At this point it's very unlikely that azbb will be offered in python; this work is no longer on our roadmap.  I'm going to close the issue as such.
