### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by jjindrich** [mspnp/template-building-blocks#342]
Hi, I'm trying to deploy simple BB, like vnet only. But getting this error:
Deployment template validation failed: 'The template resource '[concat(parameters('deploymentContext').parentTemplateUni
queString, '-vnet-', copyIndex(), '-', variables('templateUniqueString'))]' at line '30' and column '6' is invalid. The
api-version '2016-09-01' used to deploy the template does not support 'ResourceGroup' property. Please use api-version '
2017-05-10' or later to deploy the template. Please see https://aka.ms/arm-template/#resources for usage details.'.

**Comment by atoakley** [comment]
Are you using the azbb CLI and are you using the default template uri?

**Comment by jjindrich** [comment]
Sure, using azbb from npm install -g @mspnp/azure-building-blocks
and trying deploy this template - https://github.com/jjindrich/jjazure-templates/blob/master/bb-vm/deploy.json

**Comment by atoakley** [comment]
I used your parameter file and it deployed successfully.  Are you using the command in your GitHub repo to deploy it?  Does it output the tempateLink anywhere in the output?

**Comment by jjindrich** [comment]
Yes, I'm using command from GitHub. Output templates are generated successfully.

**Comment by atoakley** [comment]
Can you run "az --version" and let me know what version of the Azure CLI you have?

**Comment by jjindrich** [comment]
PS C:\> az --version
azure-cli (2.0.0)

acs (2.0.0)
appservice (0.1.1b5)
batch (0.1.1b4)
cloud (2.0.0)
component (2.0.0)
configure (2.0.0)
container (0.1.1b4)
core (2.0.0)
documentdb (0.1.1b2)
feedback (2.0.0)
iot (0.1.1b3)
keyvault (0.1.1b5)
network (2.0.0)
nspkg (2.0.0)
profile (2.0.0)
redis (0.1.1b3)
resource (2.0.0)
role (2.0.0)
sql (0.1.1b5)
storage (2.0.0)
vm (2.0.0)

Python (Windows) 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]

**Comment by atoakley** [comment]
Could you try to update your CLI?  That version is fairly old.  I successfully used your parameter file without modifications on CLI v2.0.18.

**Comment by jjindrich** [comment]
Upgraded CLI to latest version, running correctly.
There was one additional issue - I'm using account with multifactor auth. I got strange error from BB:
  error: error executing az
  status: 1
  arguments: group exists --name jjtest
But group not exist, but I found that there is issue with multifactor, I have to run az login again. Than executed successfully.
