### ISSUE TITLE
Store and Retrieve Secrets in Azure Key Vault

### ISSUE THREAD

**Issue by hgoodrow** [mspnp/template-building-blocks#343]
The patterns should be extended to show the storage and retrieval of secrets and keys using Azure Key Vault.  A good place to start is the Domain Join tutorial.

**Comment by atoakley** [comment]
@hgoodrow Is your scenario to get the secrets for the protectedSettings of the of the domain join extension?

**Comment by klasrpersson** [comment]
@atoakley That would be great.

**Comment by joecoolish** [comment]
Is this available?  I am building out a few networks for a production system and I want to store the passwords in Key Vault.  Is there any way to use Key Vault with AZBB?

**Comment by woodp** [comment]
This scenario covers the use of Key Vault for setting admin's password on a windows VM: https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-win-keyvault.json

When used in an extension it is a bit different. For example for the domain join extension it would be like this:

```
    "name": "join-ad-domain",
    "publisher": "Microsoft.Compute",
    "type": "JsonADDomainExtension",
    "typeHandlerVersion": "1.3",
    "autoUpgradeMinorVersion": true,
    "settings": {
        "Name": "contoso.com",
        "OUPath": "",
        "User": "contoso.com\\tutorialAdmin",
        "Restart": true,
        "Options": 3
    },
    "protectedSettings": {
        "reference": {
            "keyVault": {
                "id": "/subscriptions/0000000-000-000-000-00000/resourceGroups/resourceGroupName/kv/providers/Microsoft.KeyVault/vaults/keyVaultName"
            },
            "secretName": "domainjoinpass"
        }
    }
```

Then you need to set the keyvault secret to the expected JSON object. In this case "{ "Password": "yourpass" }. You can do this using az cli, e.g.:

`az keyvault secret set --name domainjoinpass --vault-name kv-name2 --value '{ \"Password\": \"yourpass\" }'
`

Do not use the portal for this as it does it's own escaping which scrambles the json.

Also please note that Key Vault must be "Enabled For Template Deployment" as described here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-keyvault-parameter

**Comment by woodp** [comment]
closing this, reopen if you have any issues

**Comment by iaingblack** [comment]
Just as a note to others, syntax should be like this, the value is enclosed in double, not single quotes;

```
az keyvault secret set --name domainjoinpass --vault-name kv-name2 --value "{ \"Password\": \"yourpass\" }"
```

**Comment by woodp** [comment]
@iaingblack actually that doesn't work for me, but single quote works fine. I'm running this from windows using a powershell cmd. How are you running it ?

**Comment by iaingblack** [comment]
I'm running in a cmd prompt (not powershell) and if I run the below I get this;

```
az keyvault secret set --name azbb-test --vault-name My-KeyVault --value '{ \"Password\": \"TestValue\" }'
az: error: unrecognized arguments: "Password": "Test Value" }'
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {keyvault} ...
```

If I run inside quotes it doesn't error. Not sure why, not a big problem obviously. Running Windows 10 and latest azbb/azurecli. 

While I got you (feel free to ignore though), any idea when keyvaults for an application gateways pfx certificate might be supported? I don't think azure in general supports it so probably unfair to ask you, but its the last hole in a completely secret based config file.
