### ISSUE TITLE
Deployment to multiple resource groups

### ISSUE THREAD

**Issue by Azurekid** [mspnp/template-building-blocks#344]
Hi,

Is there a possibility to use AZBB to deploy to multiple resources groups like you can with linked templates?

**Comment by atoakley** [comment]
@Azurekid AZBB was built with this scenario in mind.  All of the underlying templates support this scenario.  The documentation should show how to do this, but we may need to add some more information.  If you give me some information on your scenario, I can explain how to make it work.

**Comment by qkn** [comment]
Can you describe how to deploy a vNet to one resourse group and an NSG to another resource group?

**Comment by atoakley** [comment]
@qkn You have a couple of options on how to specify the resource group for your resources.  You are required to pass the resource group name on the command line.  You can consider this the "default" resource group.  If a resource group is not specified for a particular resource, this resource group will be used.  However, you can override this on a per-resource level.  If the resource groups that you specify for any of your resources do not exist, they will be created before deployment.

For your scenario, as an example, you can create your virtual network and set the resourceGroupName property within that resource to "my-vnet-rg".  Then, within your network security group resource, when you reference the virtual network, set the resourceGroupName property to "my-vnet-rg", the name to your virtual network, and list the subnets to which you want this NSG attached.  When the NSG block gets processed, it will build the resource id using the resource group, virtual network name, and subnets.

For more information, see [this page](https://github.com/mspnp/template-building-blocks/wiki/Specify-and-override-default-subscription-ID,-resource-group,-or-location) in our wiki.
