### ISSUE TITLE
Tutorial 5 fails.

### ISSUE THREAD

**Issue by qkn** [mspnp/template-building-blocks#345]
When trying to deploy tutorial 5 after previously deployed tutorial 4 it fails with the following error: `Changing property 'imageReference' is not allowed..`
tutorial-5.json contains the following lines in the AD VMs section, which makes it fail:
`                        "imageReference": {
                            "publisher": "MicrosoftWindowsServer",
                            "offer": "WindowsServer",
                            "sku": "2012-R2-Datacenter",
                            "version": "latest"
                        },`

If removed it works as expected.

**Comment by Petertaylor9999** [comment]
This is now fixed. Thanks!
