### ISSUE TITLE
Deploying a machine from Marketplace

### ISSUE THREAD

**Issue by merewind** [mspnp/template-building-blocks#350]
Im trying to deploy a VM using the following settings in parameter file:

> 
     "size":"Standard_D3_v2",
            "osType": "linux",
            "imageReference":{
                "publisher":"paloaltonetworks",
                "offer":"vmseries1",
                "sku":"byol",
                "version":"latest"
            },
            "storageAccounts":{
                "skuType": "Standard_LRS"
            }
> 

and it fails with 

> 
"Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'zzz-vm1-os'
> 

Any idea what am I missing there?

**Comment by merewind** [comment]
getting this in the error message:

``
Additional error information is available for this virtual machine:
GENERAL
Provisioning state Provisioning failed. Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'ctsbosaznwfrw01-vm1-os'.. VMMarketplaceInvalidInput
Guest agent Unknown
DISKS
ctsbosaznwfrw01-vm1-os Provisioning failed. Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'ctsbosaznwfrw01-vm1-os'.. VMMarketplaceInvalidInput
``

**Comment by luisgmsft** [comment]
@merewind, **not sure** if Marketplace Images are supported yet. Will have a look into sources.

As you can see here, some additional info is required into the ARM template for such scenarios.
https://github.com/hashicorp/packer/issues/3506

**Comment by merewind** [comment]
OK makes sense.
is that on a roadmap?
Also, it seem I can not assign the computerName to a VM either  via osProfile,  I have to use prefixes and have "_vm_n" in the name.
is there a plan to support assigning computer names directly in the code?

Thank you

**Comment by atoakley** [comment]
@merewind Sorry for the delay due to the holidays.  Support for VM plans was added in PR #357.  There is now a Boolean property on virtualMachineSettings named "usePlan".  Set it to true and it will pass the plan information along.  In addition, PR #347 had some changes with the VM names.  We still have to have a numbering scheme due to the fact you can have multiple VMs, but there is more control now.
