### ISSUE TITLE
Is there a way to not have to list VM names in the VirtualMachineExtension vms array?

### ISSUE THREAD

**Issue by dave-read** [mspnp/template-building-blocks#351]
When creating VMs that need VirtualMachineExtension(s), it looks like you have to explicitly list the names of VMs created in prior VirtualMachine sections (blocks).  For example I have 

```               
{
  "type": "VirtualMachine",
  "settings": {
      "namePrefix": "haproxy",
      "size": "Standard_D2s_v3",
      "vmCount": 2,
      ...
}
```
For VirtualMachineExtension (unless I'm missing something) I needed to expand the VM names (i.e. there's no shorthand for all the VMs created in the block):

```                   
{
  "type": "VirtualMachineExtension",
  "settings": [
      {
          "vms": [
                "haproxy-vm1","haproxy-vm2"
          ],
      ....
}
```
Then if I needed to scale up the VM count and redeploy, I'd need to make two updates?

1. Change the vmCount and 
2. Update the list of VM names

In the [samples](https://github.com/mspnp/template-building-blocks/blob/master/scenarios/tutorials/tutorial-6.json) the two AD servers play different roles, so the extensions are different, so I understand why the VM names are explicit.   However in this case the same extension with same parameters should be applied to all the VMs created within that VirtualMachine block.

I can see the benefit of having VirtualMachineExtension as a top-level section to apply across multiple groups of VMs.  However it would seem helpful to either:

- Allow reference to the namePrefix for a group of VMs created that expands to those VMs
- Allow specifying VirtualMachineExtension within the VM definition (similar to loadBalancerSettings) to have the VirtualMachineExtension apply to all of the VMs created from that definition.

**Comment by dave-read** [comment]
I'm thinking this may be a doc/schema issue?  I looked at another [example](https://github.com/mspnp/template-building-blocks/blob/master/scenarios/lb/load-balancer-public.json) and in that sample there was a nested extension property **_within_** a VM definition.  In Visual Studio Code, that attribute does not show up in code complete, but if I  manually create the property it deploy, and I see that the extension ran on each of the VMs.

**Comment by atoakley** [comment]
@dave-read You are correct.  Extensions can be specified inline in a virtual machine block, but this field is missing from the schemas used for code completion.  I have opened PR #352 to fix this.
