### ISSUE TITLE
Cannot install AZBB

### ISSUE THREAD

**Issue by FabianKLS** [mspnp/template-building-blocks#355]
Hi,

I'm trying to install the Azbb, but I receive an error message
After entering the command npm install -g @mspnp/azure-building-blocks I receive the following output:

![image](https://user-images.githubusercontent.com/15687276/33319616-a2155564-d43f-11e7-8f13-9ad6ae37ed54.png)

I'm able to install any other npm package, so I don't understand why I cannot install AZBB

**Comment by telmosampaio** [comment]
Hi Fabian, I'm having a hard time reproducing the problem. Can you check the version of npm and node you have? Also, are you running this on your local machine, or the Azure cloud shell?

**Comment by FabianKLS** [comment]
I cannot reproduce the issue, since I've reinstalled my dev workstation. Issue doesn't occur anymore. Issue can be closed.
