### ISSUE TITLE
Scenarios Multi-Tier has bad fileUri reference 

### ISSUE THREAD

**Issue by hgoodrow** [mspnp/template-building-blocks#356]
The file "extension-complete-ad1.json" has a broken link to a shared script repository that looks like it has moved.

**fileUris**": [
               "https://raw.githubusercontent.com/mspnp/reference-architectures/master/virtual-machines/n-tier-windows/extensions/adds-forest.ps1"

**Comment by telmosampaio** [comment]
Thanks, fixed.
