### ISSUE TITLE
Deploy a Linux VM in azure using azbb and generalised VM image

### ISSUE THREAD

**Issue by tsrik007** [mspnp/template-building-blocks#359]
I have a generalized Linux VM image and I want to create a new vm out of it using the azbb command.
Could someone help me with the template that I need to use for it.

**Comment by woodp** [comment]
These files on the _scenarios_ folder might help:

managed disk:
https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-lin-cust-img-managed.json
https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-lin-cust-image-managed.md

unmanaged disk:
https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-lin-cust-img-unmanaged.json
https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-lin-cust-image-unmanaged.md

**Comment by tsrik007** [comment]
Hi Woodp,

I have tried using the managed disk template for creating a linux vm.
It failed with the below error when i ran the command from azure cli.

  error: error executing az
  status: 1
  arguments: group deployment create --name bb-01-vm --resource-group resourcegroupname --template-uri https://raw.githubusercontent.com/mspnp/template-building-blocks/v2.1.0/templates/buildingBlocks/virtualMachines/virtualMachines.json --parameters @/fullpath/.npm-global/bin/azure-output.json

**Comment by tsrik007** [comment]
I see that the virtual network and virtual machine infact everything should be in the same resource group.
I tried in that way and it worked.
But in actual scenario, i have already a virtual network and it is in other resource group.
I am not sure how to create a vm in such scenario. I tried but it fails.

**Comment by woodp** [comment]
There are some limitations as to what you can place in different resource groups and locations, but these are not azbb restrictions but azure restrictions.

To use different resource groups, specify "resourceGroupName" in the root of the block, e.g.:
```
                {
                    "type": "VirtualMachine",
                    "resourceGroupName": "your-other-resource-group",
                    ...
```

Otherwise please include the error description.

**Comment by atoakley** [comment]
@tsrik007 Were you able to get this to work?  You can specify the resourceGroupName in your virtualNetwork reference on your virtual machines and the block will use that to generate the subnet reference for your NICs.

**Comment by telmosampaio** [comment]
@tsrik007 did youget it to work? I will close this issue if I do not hear back.
