### ISSUE TITLE
Parameterization of certain things

### ISSUE THREAD

**Issue by jadesai** [mspnp/template-building-blocks#368]
More of a feature request I believe. What is the recommended way of passing variables to azbb?

Use case: add AZBB as part of VS release pipeline which takes in something like -params:adminPassword=abc123 and passes it to arm template as a parameter for what might be vm password. Similar to how $AUTHENTICATION$ is done in src.

So, something like:
```
             {
                    "type": "VirtualMachine",
                    "settings": {
                        "vmCount": 1,
                        "osType": "windows",
                        "namePrefix": "jb",
                        "adminPassword": "{$adminPassword}",
                        "nics": [
                            {
                                "subnetName": "default",
                                "isPublic": true
                            }
                        ],
                        "virtualNetwork": {
                            "name": "simple-vnet"
                        }
                    }
                }
```

which could translate to the following when run as 
azbb -s "786d6510-8f1e-4ae7-b55b-5178716e6ac8" -g "jjtest707" -l westus -p adminPassword=abc123
```
				"virtualMachines": [{
					"properties": {
						"hardwareProfile": {
							"vmSize": "Standard_DS2_v2"
						},
						"osProfile": {
							"adminUsername": "adminUser",
							"secrets": [],
							"adminPassword": "abc123",
							"windowsConfiguration": {
								"provisionVmAgent": true
							},
							"computerName": "jb-vm1"
						},
						"availabilitySet": null
					},
					"name": "jb-vm1",
					"extensions": [],
					"resourceGroupName": "jjtest707",
					"subscriptionId": "786d6510-8f1e-4ae7-b55b-5178716e6ac8",
					"location": "westus",
				}]
```

**Comment by telmosampaio** [comment]
We do not support variables or parameters int he parameter file itself. But I see requests for that. I will keep this here for future reference.

**Comment by joecoolish** [comment]
I too would like to request the ability to parameterize some of the properties. Maybe have a -p flag for the template parameters and a -P flag for the parameter parameters 👍

**Comment by iaingblack** [comment]
Me too. Currently thinking of doing my own find/replace on a template file as a short term fix, but a native approach would be better.

**Comment by jocontr** [comment]
Thanks for reporting - this feature request is under review.
