### ISSUE TITLE
VM deployment fails when adminPassword is keyVaultReference

### ISSUE THREAD

**Issue by sbaryakov** [mspnp/template-building-blocks#369]
This example https://github.com/mspnp/template-building-blocks/blob/master/scenarios/vm/vm-win-keyvault.json fails with the error below

The error seems to be because location, subscribtionId and resourceGroup are added as resource properties of the KeyVaultReference and fails schema validation.

Deployment failed. Correlation ID: a72a1cb4-c02e-4727-a24a-b6864acc4d8c. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestContent\",\r\n    \"message\": \"The request content was invalid and could not be deserialized: 'Could not find member 'resourceGroupName' on object of type 'KeyVaultReference'. Path 'properties.parameters.authentication.reference.keyVault.resourceGroupName', line 1, position 1691.'.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by atoakley** [comment]
@sbaryakov Thank you for letting us know about this.  We missed this KeyVault reference when we added VM Encryption support.  PR #372 has all KeyVault references working the same way now.  The subscriptionId, resourceGroupName, and location (although it's unused here) will still be added to the KeyVault reference, but now it works like all of the rest.  I have updated the scenario as well to show this.  In short, if the KeyVault is in the same subscription and resource group, simply put the name of the KeyVault in the reference.  If it is in a different resource group, put the name and the resourceGroupName in the reference.  The building block will take care of building the id field for you.  We have some other changes that need to be released, so this PR will go out in the next update.
