### ISSUE TITLE
Connection.md in wiki is missing some required properties for localNetworkGateway

### ISSUE THREAD

**Issue by kmacphee** [mspnp/template-building-blocks#371]
GitHub doesn't seem to allow pull requests for wikis, otherwise, I would have put one in for this, but may I suggest a few edits to the **localNetworkGateway** object in **Connection.md**?

```
  - **localNetworkGateway**  
  _Object. Required when connectionType is_ `IPsec`. 
  The local network gateway to use with this connection. This resource reference object has the following properties:  
    - **name**  
    _String. Required._  
    The name of the local network gateway.
    - **ipAddress**
    _String. Required._
    The publicly addressable IP of the local network gateway.
    - **addressPrefixes**
    _Array of strings in CIDR format. Required._
    Specifies the CIDR address ranges whose traffic should be sent to the local network gateway.    
    - **subscriptionId**  
    _String in GUID format. Optional._  
    Specifies the ID of the Azure subscription that contains the local network gateway.  
    - **resourceGroupName**  
    _String. Optional._  
    Specifies the name of the resource group that contains the local network gateway.
```
Summary
- Removed the word "existing" from the **localNetworkGateway** object description. This originally lead me to believe I had to create a local network gateway outside of Building Blocks, as there is no dedicated "block" for it. However, I have tested that if the local network gateway does not exist then it gets created during the deployment, so it does not need to exist prior to the deployment.
- Added **ipAddress** and **addressPrefixes** properties. These seem to be required but absent from the wiki page, as I got validation failures when they were not included.

**Comment by Petertaylor9999** [comment]
@kmacphee - this is fixed. Thank you for your help!
