### ISSUE TITLE
problem with intrinsic functions in the keyvault

### ISSUE THREAD

**Issue by sbaryakov** [mspnp/template-building-blocks#373]
The below fails as the [concat(uniquestring(subscription().id), 'secrets'] is taken as string

                       "adminPassword": {
                            "reference": {
                                "keyVault": {
                                    "name": "[concat(uniquestring(subscription().id), 'secrets']",
                                    "resourceGroupName": "keyvault"
                                },
                                "secretName": "kvPassword"
                            }
                        },

**Comment by atoakley** [comment]
The name should be the Azure resource name of the KeyVault.  You cannot use function inline in the building blocks.

**Comment by telmosampaio** [comment]
Closing this since solution was provided
