### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory message when running azbb

### ISSUE THREAD

**Issue by mosharafMS** [mspnp/template-building-blocks#375]
After installing nodejs and npm then azbb, first time running it, I get the message 
/usr/bin/env: ‘node\r’: No such file or directory

I could reproduce it on Azure Cloud Shell and on Ubuntu 17.10

**Comment by telmosampaio** [comment]
Please install the latest version. It was a packaging issue on my side.
