### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by vincent-chartier** [mspnp/template-building-blocks#378]
Hi,

I recently came across the Building Blocks and have found the idea really useful (I have not made any production use of them yet). But as always, I continue to struggle with JSON. I guess my brain is not cut out for so many curly and square brackets. 

I really think YAML support would be a great addition to the Building Blocks. I have already implemented (about 5 new lines of code) and tested it in my own fork of the project, and find it really nice to work with. 

Do you think this would be a good candidate for a Pull Request ? This is the first time I suggest to submit one, so please advise.

Thanks
Vincent

**Comment by telmosampaio** [comment]
I am not sure what you are offering on a Pull Request. Are you offering to changing the code to use YAML?

**Comment by vincent-chartier** [comment]
I am offering to add alternative YAML support. This implies no changes to the current way the Building Blocks work.

**Comment by vincent-chartier** [comment]
Does it make sense ? To further explain, I added code to allow the user to provide  either a JSON or YAML parameters file. What do you think ?

**Comment by philemon33** [comment]
Any chance of getting an answer on this ?
Thanks.

**Comment by atoakley** [comment]
@philemon33 We are currently in the process of moving the Azure Building Blocks into the Azure CLI as an extension so development on the node version is on hold.  The main reason we went with JSON is because it is the language used by the Azure templating engine.  We will put YAML support on our backlog in the Python version.
