### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by BilBens** [mspnp/template-building-blocks#381]
Hello,
My OS is Win 7 Pro SP1 (x64).
I installed azure-cli-2.0.31  and  node-v8.11.1-x64.
when I start the installation of AZURE Building Blocks with this command **npm install -g @mspnp/azure-building-blocks** I receive this error:

****************************************
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@mspnp/azure-building-blocks' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 372ceace7bda334a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @mspnp/azure-building-blocks@latest request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443
9 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at TLSSocket.emit (events.js:211:7)
9 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
9 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
10 verbose cwd C:\windows\system32
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@mspnp/azure-building-blocks"
13 verbose node v8.11.1
14 verbose npm  v5.6.0
15 error code EACCES
16 error errno EACCES
17 error FetchError: request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443
17 error     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
17 error     at emitOne (events.js:116:13)
17 error     at ClientRequest.emit (events.js:211:7)
17 error     at TLSSocket.socketErrorListener (_http_client.js:387:9)
17 error     at emitOne (events.js:116:13)
17 error     at TLSSocket.emit (events.js:211:7)
17 error     at emitErrorNT (internal/streams/destroy.js:64:8)
17 error     at _combinedTickCallback (internal/process/next_tick.js:138:11)
17 error     at process._tickCallback (internal/process/next_tick.js:180:9)
17 error  { FetchError: request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443
17 error     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
17 error     at emitOne (events.js:116:13)
17 error     at ClientRequest.emit (events.js:211:7)
17 error     at TLSSocket.socketErrorListener (_http_client.js:387:9)
17 error     at emitOne (events.js:116:13)
17 error     at TLSSocket.emit (events.js:211:7)
17 error     at emitErrorNT (internal/streams/destroy.js:64:8)
17 error     at _combinedTickCallback (internal/process/next_tick.js:138:11)
17 error     at process._tickCallback (internal/process/next_tick.js:180:9)
17 error   message: 'request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443',
17 error   type: 'system',
17 error   errno: 'EACCES',
17 error   code: 'EACCES',
17 error   stack: 'FetchError: request to https://registry.npmjs.org/@mspnp%2fazure-building-blocks failed, reason: connect EACCES 151.101.120.162:443\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' }
18 error Please try running this command again as root/Administrator.
19 verbose exit [ 1, true ]
**************************************************

**Comment by RohitSharma-pnp** [comment]
Hi @BilBens, Did you try running as Administrator. Did it work? This looks like an npm error.

**Comment by woodp** [comment]
Closing this as it has more than 2 weeks without response. 
Reopen if's still happening.
