### ISSUE TITLE
Issue with running azbb 

### ISSUE THREAD

**Issue by tijmenvandenbrink** [mspnp/template-building-blocks#382]
Hi,

On Ubuntu 16.04.4 LTS I'm having difficulty running azbb. I installed npm and azbb the following way:

```
sudo apt-get install npm
sudo npm install -g @mspnp/azure-building-blocks
```

When I run azbb I get the following:

```
tijmen@dash:~/Projects/reference-architectures/hybrid-networking/hub-spoke$ azbb -V
/usr/local/lib/node_modules/@mspnp/azure-building-blocks/src/index.js:45
let parseParameterFile = ({parameterFile}) => {
                          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

npm version =  npm 3.5.2

Kind regards,

Tijmen

**Comment by lorax79** [comment]
Same exact issue using npm and node packages from mainline WSL Ubuntu distribution. 

NPM version: 3.5.2
NodeJS version: 4.6.2

**Comment by luisgmsft** [comment]
Hi @tijmenvandenbrink :) There was an issue with the package. Try with the latest one ([v.2.1.7](https://www.npmjs.com/package/@mspnp/azure-building-blocks))

Please let me know if this helps!

**Comment by luisgmsft** [comment]
Closing this one because of inactivity. Please re-open if you consider it. Thanks.
