### ISSUE TITLE
VNet peering across subscriptions

### ISSUE THREAD

**Issue by bgs113** [mspnp/template-building-blocks#385]
I'm attempting to create VNet peerings in a hub-and-spoke topology, with different Azure subscriptions in the same AAD tenant.  VNets are in the same Azure region (eastus).  Trying to create the peerings results in the following error, and no output files are generated:

```
$ azbb -s xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -g rgname -l eastus -p paramfile.json --deploy

  error: [{"result":false,"message":"Virtual network and peering location cannot be different"}]`
```

The parameter file section is set up like this (spoke config, redacted):

```
                            "virtualNetworkPeerings": [
                                {
                                    "name": "hub-peering",
                                    "remoteVirtualNetwork": [
                                        {
                                            "name": "hubvnetname",
                                            "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                            "resourceGroupName": "rgname"
                                        }
                                    ],
                                    "allowForwardedTraffic": true,
                                    "allowGatewayTransit": false,
                                    "useRemoteGateways": false
                                }
                            ],
```

Creating the peering with the exact same settings in the Azure Portal succeeds.

**Comment by woodp** [comment]
@bgs113 cross subscription validation has been disabled now.

You will need to separate vnet peering setup in 4 files. 
The first 2 create each of the vnets on each of the subscriptions, then the other 2 files will modify those vnets to add the peering. In each case, the main subscription is passed as a parameter to azbb. e.g.:

azbb -g peering-rg -s 0000-000-000-000-1111 -l japaneast -p vnet-peering-1.json --deploy
azbb -g peering-rg -s 0000-000-000-000-bbbb -l japaneast -p vnet-peering-2.json --deploy
azbb -g peering-rg -s 0000-000-000-000-1111 -l japaneast -p vnet-peering-3.json --deploy
azbb -g peering-rg -s 0000-000-000-000-bbbb -l japaneast -p vnet-peering-4.json --deploy

Where vnet-peering-1.json and vnet-peering-2.json sets up only the vnet
And vnet-peering-3.json and vnet-peering-4.json adds the peering.
(Note that the subscription argument is different for each run)

**Comment by woodp** [comment]
closing this, reopen if you have any issues
