### ISSUE TITLE
Request :: Automation of the Trigger to execute a building block file

### ISSUE THREAD

**Issue by saurabhseth84** [mspnp/template-building-blocks#388]
Is there a way we can automate the trigger for the building block files from a web based self-service portal or an orchestration engine?

The idea is to provide a simple web interface where users can provide the parameters that the files need and then click of a button the execution of the building block file gets triggered.
We are currently looking to provide an easy to use model of provisioning pre-defined environments for our enterprise users to help them get started and if they can do it on-demand by submitting a simple request it will be great.
The building block files will simplify the development of complex architectures and help us ensure we enforce our required defaults without any user intervention.

**Comment by hallihan** [comment]
Closing as we are not implementing new features in azbb, see note in #435
