### ISSUE TITLE
Cannot create VNET and VMs in different resource groups

### ISSUE THREAD

**Issue by iaingblack** [mspnp/template-building-blocks#391]
When creating VMs in a different resource group to the virtualnetwork they should be attached to, the nics cannot be created. Example json file here.

https://gist.github.com/iaingblack/2254370570b827f6abcb34c4126ca1ed

It seems like the wrong resource group is placed into this line in the template output for the resource;

```
"subnet": {
  "id": "/subscriptions/123mysubid456/resourceGroups/RG-Dev-VMs/providers/Microsoft.Network/virtualNetworks/dev-vnet/subnets/default"
},
```

The actual resourceid is this (part following resource groups is wrong);

`/subscriptions/123mysubid456/resourceGroups/RG-Dev-VNET/providers/Microsoft.Network/virtualNetworks/dev-vnet`

Giving this error;

`"Resource /subscriptions/3d5b86a9-f2e5-47ec-86bf-6bea5dea8f06/resourceGroups/RG-Dev-VMs/providers/Microsoft.Network/virtualNetworks/dev-vnet/subnets/default referenced by resource /subscriptions/3d5b86a9-f2e5-47ec-86bf-6bea5dea8f06/resourceGroups/RG-Dev-VMs/providers/Microsoft.Network/networkInterfaces/dev-vm-vm1-nic1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.`

Placing the vnet and VMs in the same resource groups sorts this problem as the resourceid is correct. But, means everything is jammed in one place.

Hope that makes sense. Apologies if I'm confusing anything or incorrect in my thinking.

**Comment by luisgmsft** [comment]
Hi @iaingblack :)

you can achieve what you're looking for, by specify the VNET's resource group inline, by replacing lines 40 till 42 with

`                        "virtualNetwork": {
                            "name": "dev-vnet",
                            "resourceGroupName": "lugizi-RG-Dev-VNET"
                        }` in your gist.

Please let me know it it helps.

**Comment by iaingblack** [comment]
Ah! I didn't realise that was a possibility, great! I take it that trick would work with any other 'referenced' resource so I can spread things among many resource groups as I like? I'll assume so and test when I get a chance. Thanks!!!
