### ISSUE TITLE
The Application Gateway HTTP Listener Multi-Site hostName is missing/unused

### ISSUE THREAD

**Issue by iaingblack** [mspnp/template-building-blocks#393]
When creating an app-gateway/WAF it is useful to create a multi-site (instead of basic) http listener which is listening for a DNS address and then a rule sends the request to the required backend. 

There is no mention of this hostName parameter in the httpListeners spec here;
https://github.com/mspnp/template-building-blocks/wiki/applicationGatewaySettings-Object

But, the code here seems to see it as a possibility;
https://github.com/mspnp/template-building-blocks/blob/1d9108f7bd6aeb5ed7d3a88d9eee1dff204c69b9/schemas/applicationGatewaySettings.json

```
          "httpListener": {
            "type": "object",
            "allOf": [
                {
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "frontendIPConfigurationName": {
                            "type": "string"
                        },
                        "frontendPortName": {
                            "type": "string"
                        },
                        "hostName": {
                            "type": "string"
                        }
                    }
},
```
If I include this parameter in my template the generated arm template does not have the parameter present. Is there a chance it could be included? This is one small detail which prevents azbb from being completely usable in an automatic deployment.

Thanks!

**Comment by luisgmsft** [comment]
Hi @iaingblack :) We've [published v.2.1.8 ](https://www.npmjs.com/package/@mspnp/azure-building-blocks) which includes the missing property.

Please give it a try and let us know

**Comment by iaingblack** [comment]
It works! Many thanks. I'm really enjoying using Azure building blocks, it has made setting up multiple VMs,  WAFs and follow-on provisioning steps very straightforward. Using ARM templates was getting very very complicated. Please keep it going! :) Thanks again.
