### ISSUE TITLE
No place to use and authenticationCertificate in http backend settings on App Gateway

### ISSUE THREAD

**Issue by iaingblack** [mspnp/template-building-blocks#396]
The application gateway 'backendHttpSettingsCollection' does not have a parameter to place the 'authenticationCertificate'. This means that beckend ssl encryption cannot be setup from an azbb template and something like powershell has to be used. If this could be added it would be great.

Thanks
Iain

**Comment by luisgmsft** [comment]
Hi @iaingblack :) We've taken care of this. Please upgrade to the latest version and test (https://www.npmjs.com/package/@mspnp/azure-building-blocks).

Please let me know if solves the issue you reported.

**Comment by iaingblack** [comment]
Hi. Thanks for the change. It does reference the item in the appgateway, but I think it is still missing the piece where it creates the resource. When deploying, the certificate specified cannot be found/referenced.

This is the type of thing not being generated which I think is missing (I could be wrong, but this was in a working ARM template I pulled from a working resource in azure already);

```
                "authenticationCertificates": [
                    {
                        "name": "app.awesomestuff.com",
                        "etag": "W/\"990eba48-5437-41d... etc\"",
                        "properties": {
                            "provisioningState": "Succeeded",
                            "data": "MIIFZTCCBE2gAwIBAgIQRJT/HezWcjcA... ...vL28OnEA="
                        },
                        "type": "Microsoft.Network/applicationGateways/authenticationCertificates"
                    }
                ],
```

**Comment by iaingblack** [comment]
Sorry, just to say, this is the kind of thing I have added to my template. Just in case i'm referencing this incorrectly.

The 'backendHttpSettingsCollection' property.
```
"authenticationCertificateNames": [
    "app_awesomestuff_com_localhost_selfsigned"
]
```

The referenced authenticationCertificate
```
"authenticationCertificate": [
    {
        "name": "app_awesomestuff_com_localhost_selfsigned",
        "data": "MIIDGDCCAgCg... ...0L0Bg=="
    }
],
```

**Comment by atoakley** [comment]
@iaingblack Try changing "authenticationCertificate" to "authenticationCertificates" and let me know if it works.  My sample does process and transform the certificate to the proper shape.

**Comment by luisgmsft** [comment]
Our testing was done based on what @atoakley suggests.

@iaingblack, please use "authenticationCertificates" (plural) instead and let us know.

**Comment by iaingblack** [comment]
Yup, that worked, thanks. The [docs](https://github.com/mspnp/template-building-blocks/wiki/applicationGatewaySettings-Object) refer to it without the 's' so didnt realise. 

I think that's my usecase sorted, thanks for the fixes over the past couple of weeks. Much appreciated!!!

**Comment by MikeWasson** [comment]
@iaingblack I updated the doc on the wiki

**Comment by iaingblack** [comment]
Great, thanks!
