### ISSUE TITLE
Support for App Services and App Service Environments

### ISSUE THREAD

**Issue by glloyd2010f** [mspnp/template-building-blocks#400]
Is support for App Services and App Service Environments on the road map to be included? This repo is something we are looking to leverage but we are in a massive shift to Azure PaaS resources.

**Comment by ckittel** [comment]
Thank you @glloyd2010f for the question. Not at this time. We are aware of many services not yet represented in azbb, like App Services/ASE. azbb is entering a sustain mode, and new features/services are unlikely to be added at this point.
