### ISSUE TITLE
Override hardcoded '-VM#' name suffix

### ISSUE THREAD

**Issue by iaingblack** [mspnp/template-building-blocks#401]
Is there a way to alter the behavior in this regard? I'm trying to name VMs to a convention like 'Project-Env-Role-App' and the forced ending of '_-VM#_' is robbing me of 3 characters I could use better. Could the **namePrefix** be the actual string used with the VM number appended? Or a new parameter called **nameSuffix** be created with '-vm' as a default I could override?

I realise the **computerNamePrefix** could be used to alter the actual computer name used without the '-vm' but i'd prefer to keep these matching each other if possible to reduce any confusion of the VM name vs the computer name.

Thanks
Iain

**Comment by hallihan** [comment]
Closing as we are not implementing new features in azbb, see note in #435
