### ISSUE TITLE
Broken links - Azure Building Block Tutorial -5-install-Active-Directory-using-a-VM-extension

### ISSUE THREAD

**Issue by MidiCoder** [mspnp/template-building-blocks#408]
Hi, 
I am trying to deploy the setting files in Azure Building Blocks Tutorial 5 but it keeps failing to find the powershell files for creating the new forest and add a replication site. 

The URLs mentioned in the tutorial are  

https://raw.githubusercontent.com/mspnp/reference-architectures/master/identity/adds-extend-domain/extensions/adds-forest.ps1

https://raw.githubusercontent.com/mspnp/reference-architectures/master/identity/adds-extend-domain/extensions/adds-replication-site.ps1

They are both showing as 404 not found. 

Please can someone correct this.

**Comment by Petertaylor9999** [comment]
Hi there - sorry, these are really out of date and are based on the last version of our [identity reference architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/). 

Are you trying to learn how to compose Azure building blocks templates, or are you trying to learn how to set up Active Directory in Azure?

**Comment by MidiCoder** [comment]
Hi, I am trying to learn how to use Azure Building Blocks and trying to follow the examples as set out in the tutorials. But I cant get past tutorial 5 because the link to the .ps1 files don't work.

**Comment by Petertaylor9999** [comment]
@MidiCoder - there is currently a small community, but we are trying to raise awareness of this project and grow the community through conferences and talks. We are a small team at Microsoft and we are committed to supporting this project using Github. We have plans to make more investments in the Azure Building Blocks in the near future to add new features.

If you haven't already, I highly recommend you take a look at [Azure Reference Architecutres](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/), which is another project from our team. Almost all of these reference architectures use building block templates for deployment, so you can take a look at them to see how we've used them.``

**Comment by MidiCoder** [comment]
@Petertaylor9999 - Thanks I have cloned both of the GitHub repositories and I am working on implementing the reference architectures in my lab. It would be nice to setup a forum if you haven't got one already so that we can build a community where we can discuss all things AZBB and maybe a gallery of user solutions like the ARM ones. Tell the team to keep up the good work.

**Comment by ameerhamza** [comment]
The updated links are available at this link. Just replace the links from ad-vm1, ad-vm2 in json in tutorial with links from following and it works like a charm

https://github.com/mspnp/reference-architectures/blob/master/virtual-machines/n-tier-windows/n-tier-windows.json

**Comment by MidiCoder** [comment]
@ameerhamza I will try it as soon as I can and get back to you. 

Thanks

**Comment by MidiCoder** [comment]
@ameerhamza 

Hi, I updated the links for ad-vm1 and ad-vm2 but the deployment is failing when it gets to the install-adds extension on ad-vm2. 

I have logged into ad-vm2 and I can see that the VM has joined the contoso domain but it has not installed ADDS. 

The VM is reporting a failure when processing extension 'install-adds'. 

But the script works fine if I run it on a local machine. 

This is the error that I am getting : 

"code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n
     \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'install-adds'. Error message: \\\"Finished executing command\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"

**Comment by ameerhamza** [comment]
Hi,

I don't have a subscription and it's very expensive to experiment further ;)
I got the same problem as well. I think it went away with further tweaks as far as I recall. I am new to all this and don't recall what the tweaks were. 

My advice would be to see the reference architecture template from where you copied the link. I think its a working example 

Regards

**Comment by woodp** [comment]
Both [n-tier windows reference architecture](https://github.com/mspnp/reference-architectures/blob/master/virtual-machines/n-tier-windows/n-tier-windows.json) and [tutorial 5](https://github.com/mspnp/template-building-blocks/blob/master/scenarios/tutorials/tutorial-5.json) have been updated.
