### ISSUE TITLE
Missing Virtual Network Property reference in documentation.

### ISSUE THREAD

**Issue by MidiCoder** [mspnp/template-building-blocks#409]
Hi I don't know if it my eyes that are playing me up. But I can't find any reference to the Virtual Network property of the Azure Building Block (Virtual Machine) in the documentation.  

Please see this page - 
https://github.com/mspnp/template-building-blocks/wiki/Virtual-Machines

VSC is complaining that I am missing it, and I can also see that it is being used in other examples elsewhere so it has to exist.

**Comment by Petertaylor9999** [comment]
So sorry - that goes in the "settings" section. I don't know how I missed that, but I've fixed the document.
