### ISSUE TITLE
Error executing az status: null - vm list-skus --resource-type virtualMachines --zone false --subscription

### ISSUE THREAD

**Issue by vicperdana** [mspnp/template-building-blocks#418]
Appreciate any assistance.  

I am on azbb version 2.2.3 and cli 2.0.74.

Trying to deploy the following https://github.com/mspnp/reference-architectures/blob/master/hybrid-networking/shared-services-stack/shared-services-stack.json according to the instructions https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/shared-services

```
azbb -s "xxxxxx-xxxxx-xxxxx-xxxx-xxxxxx" -g onprem-vnet-rg -l eastus -p .\shared-services-stack.json --deploy

  error: error executing az
  message:
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription 6xxxxx-xxxx-xxxxx-xxxxxx-xxxxx
```

**Comment by egulatee** [comment]
Running into the same issue.
Az Cli 2.0.75
Azbb 2.2.3

Vm list-skus command returns successfully run via  az instead azbb

**Comment by egulatee** [comment]
I added debugging to the building blocks code.  (--debug wasn't helpful)
I am getting a child.signal = SIGTERM when spawnSync is being executed on the list-skus.  
-Supposedly that's tied to timeouts but I tried raising the timeouts and nothing.
-I verified the the spawnSync is using shell = true . (Something else people suggest)

I did notice there's a lot of output going to stdout from az vm list-skus.  I'm wondering if we're hitting some output size.  (I print the stdout and it's incomplete JSON and seems to fails at the same point in 3 runs)

My current thiking it's due to JSON size returned by az list.  I'll see whether I can fix/confirm.

**Comment by egulatee** [comment]
Confirmed.  Changing the maxbuffer size in azCLI.js's spawnAz function solved the issue.

**Comment by nikhillotia** [comment]
can you please share location as where to do below changes?

 Changing the maxbuffer size in azCLI.js's spawnAz function solved the issue.

AZBB's default is 1024x1024. I raised it to 1024x1024x10 and it worked.

**Comment by tylerd** [comment]
Hello, I updated the following block in azCLI.js and it seemed to work, adding the maxBuffer line

```javascript
spawnOptions = spawnOptions || {
        stdio: 'pipe',
        shell: true,
        maxBuffer : 1024*1024*10
    };
```

**Comment by tylerd** [comment]
#423 Pull Request

**Comment by vipulkshah** [comment]
Hi, I am getting the same. Please share me the steps to update buffer size in azCLI.js. I couldn't found it. Thank You

**Comment by ravibak** [comment]
I tried adding the suggested block in azCLI.js file from the folder below on my machine but getting the same error..

C:\Users\<userid>\AppData\Roaming\npm\node_modules\@mspnp\azure-building-blocks\src

**Comment by ravibak** [comment]
I had to increase the maxBuffer to 1024*1024*20 to make it work.

**Comment by bradcstevens** [comment]
Running into the same issue and regardless of setting the maxBuffer to `1024*1024*10` or to `1024*1024*20` 

Az Cli 2.1.0
Azbb 2.2.3

Vm list-skus command returns successfully run via az instead azbb

**Comment by PabloCastilloG** [comment]
I changed maxbuffer, adding 1024*1024*20 and it work.

Az Cli 2.1.0
Azbb 2.2.3

=========
spawnOptions = spawnOptions || {
        stdio: 'pipe',
        shell: true,
        maxBuffer : 1024*1024*10
    };

**Comment by gvnshtn** [comment]
I'm still seeing this error, have confirmed I have the maxBuffer set to 1024 * 1024 * 100
