### ISSUE TITLE
ERROR: az: error: unrecognized arguments: --subscription trying Tutorial 1 deploy a simple VNet

### ISSUE THREAD

**Issue by acanequeisban** [mspnp/template-building-blocks#419]
Hi all,
Trying [Tutorial 1 deploy a simple VNet](https://github.com/mspnp/template-building-blocks/wiki/Tutorial-1-deploy-a-simple-VNet) I got the following error:

ERROR: az: error: unrecognized arguments: --subscription  ......... 

I'm in windows 10 enterprise, with  az azure-cli (2.0.27)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\XXXXX\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

and azbb 2.2.3, 

[errorAZ.txt](https://github.com/mspnp/template-building-blocks/files/3737898/errorAZ.txt)

Hope this info can help you!!

Regards

**Comment by atoakley** [comment]
The version of the CLI that you are using is very old. The global subscription parameter was added in v2.0.38. Please upgrade your CLI version and test again. If that doesn't fix it, please reopen the issue.

**Comment by acanequeisban** [comment]
Perfect many thanks!!!
