### ISSUE TITLE
When output of az cli is set to table azbb commands fail

### ISSUE THREAD

**Issue by rakeshvanga** [mspnp/template-building-blocks#422]
I have the default output of my `az cli` to be a table. So, when running the `azbb` commands, it is not able to read the regions because it is not able to understand the table output format.
Considering passing `--json` in azbb code when running az cli commands as every user might have different defaults set to their az cli's output.

**Comment by marcosgm** [comment]
+1. This is the error when AZ CLI is set to table:

  **error: error retrieving locations
message: Unexpected token R in JSON at position 0**

And this is how I fixed it by changing AZ CLI

># az configure
(...)
> [core]
> first_run = yes
> collect_telemetry = no
> output = table
> 
> [logging]
> enable_log_file = no
> 
> Do you wish to change your settings? (y/N): y
> 
> What default output format would you like?
>  [1] json - JSON formatted output that most closely matches API responses.
>  [2] jsonc - Colored JSON formatted output that most closely matches API responses.
>  [3] table - Human-readable output format.
>  [4] tsv - Tab- and Newline-delimited. Great for GREP, AWK, etc.
>  [5] yaml - YAML formatted output. An alternative to JSON. Great for configuration files.
>  [6] none - No output, except for errors and warnings.
> Please enter a choice [Default choice(3)]: 1
> 

Once it's set as JSON, azbb works fine
