### ISSUE TITLE
cannot deploy vm to region switzerlandnorth

### ISSUE THREAD

**Issue by giarbi** [mspnp/template-building-blocks#424]
cannot deploy vm to region switzerlandnorth even the sku is available in the region and manuel doplyment is working fine.
![Annotation 2019-12-29 075941](https://user-images.githubusercontent.com/13151763/71553574-295d9c00-2a12-11ea-8bd3-f7cc4ff6fc9b.jpg)
![Annotation 2019-12-29 075823](https://user-images.githubusercontent.com/13151763/71553576-2c588c80-2a12-11ea-9351-d69f1de37a0f.jpg)

**Comment by absheik** [comment]
VM deployment was recently fixed by #420. We need to publish an update of the npm package. We will schedule it for an upcoming sprint. If you clone, build and run locally you can get past this error.
