### ISSUE TITLE
cannot deploy VNet

### ISSUE THREAD

**Issue by rramoscabral** [mspnp/template-building-blocks#426]
Hi, I have problem deploying VNet, error:

Attempting to read file C:\temp\M01-01_01-Azure
File Error: Failed to open C:\temp\M01-01_01-Azure, assume not a file
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x037A6CD8>, <function CLIQuery.handle_query_parameter at 0x037D1DB0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03ACD930>, <function handler 
at 0x04767B28>]
cli.azure.cli.core.util : Unable to parse parameter: @C:\temp\M01-01_01-Azure
Unable to parse parameter: @C:\temp\M01-01_01-Azure
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2524 in cache
telemetry.check : Negative: The C:\Users\Admin\.azure\telemetry.txt was modified at 2020-01-28 23:28:29.102304, which in less than 600.000000 s
command ran in 3.375 seconds.

  error: error executing az
  status: 1

I have CLI updated. The folder has spaces. Maybe this is the problem.

**Comment by rramoscabral** [comment]
Test with a path without spaces there are no problems. I cannot run on a folder with spaces.

**Comment by absheik** [comment]
closing the issue as no action needed
