### ISSUE TITLE
Unable to use AZBB to deploy a VM

### ISSUE THREAD

**Issue by jesseloudon** [mspnp/template-building-blocks#427]
## Issue Description
I was able to successfully deploy a single VNET using AZBB.
But when running AZBB again to deploy a single VM it's failing with below error.

## Error
azbb -g "Lab1-RG" -s "e8816010-d0e5-4021-944a-20d9e9978365" -l "australiaeast" -p "C:\Temp\Scripts\Lab1-singlevm.json" --deploy

  error: error executing az
  message:
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription e8816010-d0e5-4021-944a-20d9e9978365

## Client versions I'm using
`azbb -V`
2.2.3

`npm -v`
6.13.4

`node -v`
v12.16.1

`az version`
{
  "azure-cli": "2.1.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.1.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aks-preview": "0.4.32",
    "azure-firewall": "0.1.8",
    "interactive": "0.4.1"
  }
}

## JSON file used

{
  "$schema": "https://raw.githubusercontent.com/mspnp/template-building-blocks/master/schemas/buildingBlocks.json",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "buildingBlocks": {
      "value": [
        {
            "type": "VirtualMachine",
            "settings": {
            "vmCount": 2,
            "osType": "windows",
            "namePrefix": "APPFE",
            "adminUsername": "localadmin",
            "adminPassword": "Wh@t$aP@$$w0rd?",
            "nics":[
                {
                    "subnetName": "AppFrontEnd-SN",
                    "isPublic": false
                }
            ],
            "virtualNetwork": {
                "name": "WUS2-IaaS-VNET"
            }
            }
        }
      ]
    }
  }
}

**Comment by absheik** [comment]
I was able to reproduce your error.  It was recently fixed by https://github.com/mspnp/template-building-blocks/pull/420.  We need to publish an update of the npm package.  We will schedule it for an upcoming sprint.  If you clone, build and run locally you can get past this error.  I am able to run up to **tutorial 5** locally.
