### ISSUE TITLE
Availability set issue

### ISSUE THREAD

**Issue by peakers76** [mspnp/template-building-blocks#430]
I notice when deploying any JSON templates where more than one machine is deployed which are then added to an Availability set the deployment always fails at that point where the VM is added to the availability set.

The output from the VS code window shows the error which references the Availability set as the cause for the failure to the overall deployment. What I notice is the "Resource ID" is incorrect "providers/Microsoft.Network/availabilitySets/ad-as is not a valid resource reference" 

When checking the availability set created from the azbb deployment i noticed that the provider path is identical except one section /providers/Microsoft.Compute/availabilitySets/ad-as. The correct path uses "Microsoft.Compute" the failed resource ID in the failure message references "Microsoft.network"

Can someone please let me know if this is a bug in the code? If you would like to deploy the same Json file i used the "tutorial-4.json" file from the Tutorials section in the Github code.

Thank you

**Comment by magrande** [comment]
@peakers76  I was able to run tutorial-4.json without any issues. I also don't see the that availability sets are being included in this example. Can you provide more context, to help us troubleshoot this more for you, please do so. If this is no longer an issue for you, you can close this.

**Comment by magrande** [comment]
Closing the issue at this time. You're totally welcome to reopen this or create a new one. if you can, please provide the additional details to help us troubleshoot.
