### ISSUE TITLE
azbb.ps1 cannot be loaded

### ISSUE THREAD

**Issue by cherchyk** [mspnp/template-building-blocks#434]
Hi,

Can someone teach me how to handle ".ps1 is not digitally signed" situation?

```
PS C:\WINDOWS\system32> npm install -g @mspnp/azure-building-blocks
>>
C:\Users\name\AppData\Roaming\npm\azbb -> C:\Users\name\AppData\Roaming\npm\node_modules\@mspnp\azure-building-blocks\src\index.js
+ @mspnp/azure-building-blocks@2.2.3
updated 1 package in 1.925s
PS C:\WINDOWS\system32> azbb -V
>>
azbb : File C:\Users\name\AppData\Roaming\npm\azbb.ps1 cannot be loaded. The file
C:\Users\name\AppData\Roaming\npm\azbb.ps1 is not digitally signed. You cannot run this script on the current
system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ azbb -V
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by ckittel** [comment]
Sure @cherchyk.  PowerShell evaluates your local "Execution Policy" to apply restrictions on what can or cannot be executed on the local environment.  Based on your error message, it looks like your environment is applying a restriction that says local files must be signed.  You can check your current user's policy status by running `Get-ExecutionPolicy -List` to see what it is set to for `CurrentUser` or your machine - it might be directly/indirectly set to `AllSigned` or `Restricted`.  You can then execute [`Set-ExecutionPolicy -ExecutionPolicy <policy>`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7) to whatever level is appropriate for your environment/user.  The most wide-open policy that you can set is `Bypass` but more often folks go with `RemoteSigned` as that requires all remote scripts to be at least signed - but allows local scripts that you've brought onto your machine (like `azbb.ps1`) to be executed without being signed.

**Comment by hallihan** [comment]
@cherchyk - let us know if you need further assistance, I'm closing this issue since there has not been any update.
