### ISSUE TITLE
update building blocks to support sovereign clouds

### ISSUE THREAD

**Issue by devkeydet** [mspnp/template-building-blocks#44]
It would great if you could improve these templates so those who use AzureChinaCloud, AzureUSGovernment, and AzureGermanCloud can use them as well.

I forked and made some brute force changes to quickly get the n-tier reference architecture working in Azure Government:
https://github.com/devkeydet/reference-architectures
https://github.com/devkeydet/template-building-blocks

Most of the incompatibilities include hard coded storage endpoints in templates.  Guidance on fixing this is available in at:
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-manage-marketplace-partners

Another major incompatibility is using fixed values for VM sizes.  For example "Standard_DS1_v2" is not available in all sovereign cloud regions.  Parameterizing these values would allow the user to make the choice at deployment time.

**Comment by telmosampaio** [comment]
Please check our v2: https://github.com/mspnp/template-building-blocks/wiki/command-line-reference
The cloud parameter allows you to specify usage for sovereign, government, and private clouds.
