### ISSUE TITLE
Availability Set not created if less than 2 VMs are created by multi-vm-n-nic-m-storage 

### ISSUE THREAD

**Issue by pstork** [mspnp/template-building-blocks#68]
If you create a VM using this building block and only specify that one VM be created then an Availabilty set is not created even if you specify "No" for "useExistingAvailabilitySet".  Is that by design?  I know that an availability set with only one VM doesn't do anything.  But the current behavior precludes creating one VM with an availability set and then creating a second one later and adding it to the existing availability set, because its not there.

**Comment by telmosampaio** [comment]
This is by design.
